package translate.codegen

import grammar.token.Token
import structure.ASTNode
import translate.meta.MetaBaseVisitor
import translate.meta.MetaDescription

class DescriptionBuilder(
    private val packageName: String,
    private val objectName: String
) : MetaBaseVisitor<String>() {

    override fun <T : Token> collect(root: ASTNode<T>): String {
        val collected = visit(root)
        return """/**
This code is generated by [translate.codegen.DescriptionBuilder]
deriving from base class [translate.meta.MetaBaseVisitor] generated by [translate.codegen.VisitorBuilder]
*/

package $packageName

import grammar.token.Token
import grammar.Grammar
import grammar.Expansion
import structure.Description

object ${objectName}Description {
$collected
}
"""
    }

    override fun <T : Token> visitTerminal(token: T): String {
        return token.toString()
    }

    override fun visit_all(node: ASTNode.InnerNode<MetaDescription.all>): String {
        return ""
    }

    override fun visit_m(node: ASTNode.InnerNode<MetaDescription.m>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_t(node: ASTNode.InnerNode<MetaDescription.t>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_g(node: ASTNode.InnerNode<MetaDescription.g>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_kfPlus(node: ASTNode.InnerNode<MetaDescription.kfPlus>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_tComp(node: ASTNode.InnerNode<MetaDescription.tComp>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_tFrag(node: ASTNode.InnerNode<MetaDescription.tFrag>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_tPlus(node: ASTNode.InnerNode<MetaDescription.tPlus>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_tSkip(node: ASTNode.InnerNode<MetaDescription.tSkip>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_tArray(node: ASTNode.InnerNode<MetaDescription.tArray>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_tArrayPlus(node: ASTNode.InnerNode<MetaDescription.tArrayPlus>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_tLine(node: ASTNode.InnerNode<MetaDescription.tLine>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_tDef(node: ASTNode.InnerNode<MetaDescription.tDef>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_gComp(node: ASTNode.InnerNode<MetaDescription.gComp>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_gPlus(node: ASTNode.InnerNode<MetaDescription.gPlus>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_gSynth(node: ASTNode.InnerNode<MetaDescription.gSynth>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_gInh(node: ASTNode.InnerNode<MetaDescription.gInh>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_gCompv(node: ASTNode.InnerNode<MetaDescription.gCompv>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_gStart(node: ASTNode.InnerNode<MetaDescription.gStart>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_attribs(node: ASTNode.InnerNode<MetaDescription.attribs>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_attrib(node: ASTNode.InnerNode<MetaDescription.attrib>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_attribsPlus(node: ASTNode.InnerNode<MetaDescription.attribsPlus>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_type(node: ASTNode.InnerNode<MetaDescription.type>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_setDef(node: ASTNode.InnerNode<MetaDescription.setDef>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_defValue(node: ASTNode.InnerNode<MetaDescription.defValue>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_gLine(node: ASTNode.InnerNode<MetaDescription.gLine>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_def(node: ASTNode.InnerNode<MetaDescription.def>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_rules(node: ASTNode.InnerNode<MetaDescription.rules>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_rule(node: ASTNode.InnerNode<MetaDescription.rule>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_rulesPlus(node: ASTNode.InnerNode<MetaDescription.rulesPlus>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_seq(node: ASTNode.InnerNode<MetaDescription.seq>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_atom(node: ASTNode.InnerNode<MetaDescription.atom>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_seqPlus(node: ASTNode.InnerNode<MetaDescription.seqPlus>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_pass(node: ASTNode.InnerNode<MetaDescription.pass>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_defBody(node: ASTNode.InnerNode<MetaDescription.defBody>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_defAtom(node: ASTNode.InnerNode<MetaDescription.defAtom>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_defPlus(node: ASTNode.InnerNode<MetaDescription.defPlus>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_defTerm(node: ASTNode.InnerNode<MetaDescription.defTerm>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_defMod(node: ASTNode.InnerNode<MetaDescription.defMod>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_atName(node: ASTNode.InnerNode<MetaDescription.atName>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun visit_op(node: ASTNode.InnerNode<MetaDescription.op>): String {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

}