package translate.codegen

import grammar.Expansion
import grammar.Grammar
import grammar.token.Token
import structure.ASTNode
import structure.Walker
import translate.codegen.helpers.GrammarInfo
import translate.codegen.helpers.BuilderHelper
import translate.meta.helpers.MetaGrammarInfo
import utils.Beautifier

class WalkerBuilder(
    private val packageName: String,
    private val grammarInfoObject: GrammarInfo
) : BuilderHelper {

    private val packagePath = packageName.replace(".", "\\")
    private val interfaceName = "${grammarInfoObject.getSimpleName()}WalkerBase"

    override fun getDefinedTokens(): List<Token> {
        return grammarInfoObject.getDefinedTokens()
    }

    override fun getFullName(token: Token): String {
        return "${grammarInfoObject.getName()}.$token"
    }

    override fun getVisitMethods(token: Token): String {
        return when (token) {
            is Token.StateToken -> getStateVisitMethods(token)
            else -> getTerminalVisitMethods(token)
        }
    }

    private fun getStateVisitMethods(token: Token.StateToken): String {
        val expansions = grammarInfoObject.getGrammar().RULES[token].expansions
        return if (expansions.size == 1) {
            """
    /**
    $token -> ${expansions.first()}
    */
    fun visit_${token}(node: ${getNodeType(token)}): R {
        throw IllegalStateException("Unexpected expansion ${"$"}{node.getToken()} -> ${"$"}{node.getExpansion()} visited while visiting traversing tree")
    }"""
        } else {
            """
    fun visit_${token}(node: ${getNodeType(token)}): R {
        return when (val id = node.getExpansion().getId()) {
${expansions.joinToString("\n") { "\t\t\t${it.getId()} -> visit_${token}_${it.getId()}(node)" }}
            else -> throw IllegalStateException("Unexpected expansion id ${"$"}id in expansion of $token")
        }
    }
${expansions.joinToString("\n") {
                """
    /**
    $token -> $it
    */
    fun visit_${token}_${it.getId()}(node: ${getNodeType(token)}): R {
        throw IllegalStateException("Unexpected expansion ${"$"}{node.getToken()} -> ${"$"}{node.getExpansion()} visited while visiting traversing tree") 
    }"""
            }}"""
        }
    }

    private fun getTerminalVisitMethods(token: Token): String {
        return """
    fun visit_${token}(node: ${getNodeType(token)}): R {
        return visitTerminal(node.getToken())
    }"""
    }

    override fun getChoiceVisit(): String {
        return """
    override fun visit(node: ${className(ASTNode::class)}<out ${className(Token::class)}>): R {
        return when(node.getToken()) {
${getDefinedTokens().joinToString("\n") { "\t\t\t${getFullName(it)} -> visit_${it}(node as ${getNodeType(it)})" }}
            else -> throw IllegalStateException("Unknown token ${"$"}{node.getToken()} met")
        }
    }"""
    }

    override fun getAll(): String {
        Token.switchTo(grammarInfoObject.getName())
        return Beautifier.detabify(
            """/**
This code is generated by [${WalkerBuilder::class.qualifiedName}]
basing on grammar description [${grammarInfoObject::class.qualifiedName}] derived from [${GrammarInfo::class.qualifiedName}]
*/

package $packageName

import ${Token::class.qualifiedName}
import ${Grammar::class.qualifiedName}
import ${Expansion::class.qualifiedName}

import ${ASTNode::class.qualifiedName}
import ${Walker::class.qualifiedName}

import ${BuilderHelper::class.qualifiedName}
import ${MetaGrammarInfo::class.qualifiedName}

@Suppress("UNCHECKED_CAST")
interface $interfaceName<R> : ${className(Walker::class)}<R> {

/*
${grammarInfoObject.getGrammar()}
*/
${getVisitTerminal()}
${getChoiceVisit()}
${getVisitMethods()}

}"""
        )
    }

}