package translate.meta.helpers

import grammar.token.Token
import structure.ASTNode
import structure.Visitor
import translate.codegen.helpers.GrammarInfo
import translate.codegen.helpers.BuilderHelper
import utils.Beautifier

object MetaVisitorBuilder : BuilderHelper {

    private const val packageName = "translate.meta"
    private const val grammarPackageName = "translate.meta.helpers"
    private val className = "Meta${Beautifier.className(Visitor::class)}Base"
    private val grammarInfo = MetaGrammarInfo

    override fun getDefinedTokens(): List<Token> {
        return grammarInfo.getDefinedTokens()
    }

    override fun getFullName(token: Token): String {
        return "${grammarInfo.getName()}.$token"
    }

    override fun getVisitMethods(token: Token): String {
        return when (token) {
            is Token.StateToken -> getStateVisitMethods(
                token
            )
            else -> getTerminalVisitMethods(token)
        }
    }

    override fun getChoiceVisit(): String {
        return """
    override fun visit(node: ${className(ASTNode::class)}<out ${className(Token::class)}>, value: A): R {
        return when(node.getToken()) {
${getDefinedTokens().joinToString("\n") { "\t\t\t${getFullName(it)} -> visit_${it}(node as ${getNodeType(it)}, value)" }}
            else -> throw IllegalStateException("Unknown token ${"$"}{node.getToken()} met")
        }
    }"""
    }

    private fun getStateVisitMethods(token: Token.StateToken): String {
        val expansions = grammarInfo.getGrammar().RULES[token].expansions
        return if (expansions.size == 1) {
            """
    /**
    $token -> ${expansions.first()}
    */
    fun visit_${token}(node: ${getNodeType(token)}, value: A): R {
        throw IllegalStateException("Unexpected expansion ${"$"}{node.getToken()} -> ${"$"}{node.getExpansion()} visited while visiting traversing tree")
    }"""
        } else {
            """
    fun visit_${token}(node: ${getNodeType(token)}, value: A): R {
        return when (val id = node.getExpansion().getId()) {
${expansions.joinToString("\n") { "\t\t\t${it.getId()} -> visit_${token}_${it.getId()}(node, value)" }}
            else -> throw IllegalStateException("Unexpected expansion id ${"$"}id in expansion of $token")
        }
    }
${expansions.joinToString("\n") {
                """
    /**
    $token -> $it
    */
    fun visit_${token}_${it.getId()}(node: ${getNodeType(token)}, value: A): R {
        throw IllegalStateException("Unexpected expansion ${"$"}{node.getToken()} -> ${"$"}{node.getExpansion()} visited while visiting traversing tree") 
    }
"""
            }}"""
        }
    }

    private fun getTerminalVisitMethods(token: Token): String {
        return """
    fun visit_${token}(node: ${getNodeType(token)}, value: A): R {
        return visitTerminal(node.getToken())
    }"""
    }

    override fun getAll(): String {
        return Beautifier.detabify(
            """/**
This code is generated by [${MetaVisitorBuilder::class.qualifiedName}] derived from [${BuilderHelper::class.qualifiedName}]
based on grammar description [${MetaGrammarInfo::class.qualifiedName}] derived from [${GrammarInfo::class.qualifiedName}]
*/

package $packageName

import ${Visitor::class.qualifiedName}
import ${ASTNode::class.qualifiedName}
import ${Token::class.qualifiedName}
import $grammarPackageName.${grammarInfo.getName()}

@Suppress("UNCHECKED_CAST")
interface $className<R, A> : ${className(Visitor::class)}<R, A> {

/*
${grammarInfo.getGrammar()}
*/
${getVisitTerminal()}
${getChoiceVisit()}    
${getVisitMethods()}

}"""
        )
    }

}
