/**
This code is generated by [translate.codegen.WalkerBuilder]
basing on grammar description [translate.meta.helpers.MetaGrammarInfo] derived from [translate.codegen.helpers.GrammarInfo]
*/

package translate.meta

import grammar.token.Token
import grammar.Grammar
import grammar.Expansion

import structure.ASTNode
import structure.Walker

import translate.codegen.helpers.BuilderHelper
import translate.meta.helpers.MetaGrammarInfo

@Suppress("UNCHECKED_CAST")
interface MetaWalkerBase<R> : Walker<R> {

/*
Start: all
all -> m t g
m -> MACRO LPAREN kfPlus RPAREN | <eps>
kfPlus -> KOTLIN_FUNC kfPlus | <eps>
t -> TOKENS LPAREN tComp tFrag tPlus RPAREN
tComp -> COMPANION LPAREN tSkip RPAREN | <eps>
tSkip -> SKIP DESCRIBE tArray EOLN
tArray -> LARRAY CAPSNAME tArrayPlus RARRAY
tArrayPlus -> SEP CAPSNAME tArrayPlus | <eps>
tFrag -> FRAGMENTS LPAREN tFragPlus RPAREN | <eps>
tFragPlus -> tFragLine tFragPlus | <eps>
tFragLine -> CAPSNAME DESCRIBE STRING EOLN
tPlus -> tLine tPlus | <eps>
tLine -> CAPSNAME DESCRIBE tDef EOLN
tDef -> STRING | RSTRING | LTRIG CHAR CHARRANGE CHAR RTRIG
g -> GRAMMAR LPAREN gComp gPlus RPAREN
gComp -> COMPANION LPAREN gSynth gInh gCompv gStart RPAREN
gSynth -> SYNTHESIS LPAREN attribs RPAREN | <eps>
gInh -> INHERITANCE LPAREN attribs RPAREN | <eps>
gCompv -> COMPUTE LPAREN attribs RPAREN | <eps>
gStart -> START DESCRIBE CAMELNAME EOLN
attribs -> attrib attribsPlus
attrib -> CAMELNAME DESCRIBE type setDef EOLN
type -> INT_TYPE | DOUBLE_TYPE | STRING_TYPE
setDef -> DEFINE LPAREN DEFAULT ASSIGN defValue RPAREN | <eps>
attribsPlus -> attrib attribsPlus | <eps>
gPlus -> gLine gPlus | <eps>
gLine -> CAMELNAME def DESCRIBE rules EOLN
rules -> rule rulesPlus
rule -> seq def
seq -> atom seqPlus
atom -> CAPSNAME | CAMELNAME pass
pass -> LPAREN defBody RPAREN | <eps>
seqPlus -> atom seqPlus | <eps>
rulesPlus -> CHOICE rule rulesPlus | <eps>
def -> DEFINE LPAREN defBody RPAREN | <eps>
defBody -> defAtom defPlus
defAtom -> CAMELNAME ASSIGN defValue
defValue -> STRING | defTerm defMod | SUB defTerm
defTerm -> atName | INT | DOUBLE
defMod -> op defTerm | <eps>
op -> ADD | SUB | MUL | DIV
atName -> SPNAME | CAMELNAME | MACROREF CAMELNAME LBRACKET defValue RBRACKET
defPlus -> SEP defAtom defPlus | <eps>
*/

    fun <T : Token> visitTerminal(token: T): R

    override fun visit(node: ASTNode<out Token>): R {
        return when(node.getToken()) {
            MetaGrammarInfo.LPAREN -> visit_LPAREN(node as ASTNode.TerminalNode<MetaGrammarInfo.LPAREN>)
            MetaGrammarInfo.RPAREN -> visit_RPAREN(node as ASTNode.TerminalNode<MetaGrammarInfo.RPAREN>)
            MetaGrammarInfo.EOLN -> visit_EOLN(node as ASTNode.TerminalNode<MetaGrammarInfo.EOLN>)
            MetaGrammarInfo.DEFINE -> visit_DEFINE(node as ASTNode.TerminalNode<MetaGrammarInfo.DEFINE>)
            MetaGrammarInfo.DESCRIBE -> visit_DESCRIBE(node as ASTNode.TerminalNode<MetaGrammarInfo.DESCRIBE>)
            MetaGrammarInfo.CHOICE -> visit_CHOICE(node as ASTNode.TerminalNode<MetaGrammarInfo.CHOICE>)
            MetaGrammarInfo.LTRIG -> visit_LTRIG(node as ASTNode.TerminalNode<MetaGrammarInfo.LTRIG>)
            MetaGrammarInfo.RTRIG -> visit_RTRIG(node as ASTNode.TerminalNode<MetaGrammarInfo.RTRIG>)
            MetaGrammarInfo.CHARRANGE -> visit_CHARRANGE(node as ASTNode.TerminalNode<MetaGrammarInfo.CHARRANGE>)
            MetaGrammarInfo.ASSIGN -> visit_ASSIGN(node as ASTNode.TerminalNode<MetaGrammarInfo.ASSIGN>)
            MetaGrammarInfo.ADD -> visit_ADD(node as ASTNode.TerminalNode<MetaGrammarInfo.ADD>)
            MetaGrammarInfo.SUB -> visit_SUB(node as ASTNode.TerminalNode<MetaGrammarInfo.SUB>)
            MetaGrammarInfo.MUL -> visit_MUL(node as ASTNode.TerminalNode<MetaGrammarInfo.MUL>)
            MetaGrammarInfo.DIV -> visit_DIV(node as ASTNode.TerminalNode<MetaGrammarInfo.DIV>)
            MetaGrammarInfo.LARRAY -> visit_LARRAY(node as ASTNode.TerminalNode<MetaGrammarInfo.LARRAY>)
            MetaGrammarInfo.RARRAY -> visit_RARRAY(node as ASTNode.TerminalNode<MetaGrammarInfo.RARRAY>)
            MetaGrammarInfo.SEP -> visit_SEP(node as ASTNode.TerminalNode<MetaGrammarInfo.SEP>)
            MetaGrammarInfo.LBRACKET -> visit_LBRACKET(node as ASTNode.TerminalNode<MetaGrammarInfo.LBRACKET>)
            MetaGrammarInfo.RBRACKET -> visit_RBRACKET(node as ASTNode.TerminalNode<MetaGrammarInfo.RBRACKET>)
            MetaGrammarInfo.MACRO -> visit_MACRO(node as ASTNode.TerminalNode<MetaGrammarInfo.MACRO>)
            MetaGrammarInfo.TOKENS -> visit_TOKENS(node as ASTNode.TerminalNode<MetaGrammarInfo.TOKENS>)
            MetaGrammarInfo.GRAMMAR -> visit_GRAMMAR(node as ASTNode.TerminalNode<MetaGrammarInfo.GRAMMAR>)
            MetaGrammarInfo.FRAGMENTS -> visit_FRAGMENTS(node as ASTNode.TerminalNode<MetaGrammarInfo.FRAGMENTS>)
            MetaGrammarInfo.COMPANION -> visit_COMPANION(node as ASTNode.TerminalNode<MetaGrammarInfo.COMPANION>)
            MetaGrammarInfo.SKIP -> visit_SKIP(node as ASTNode.TerminalNode<MetaGrammarInfo.SKIP>)
            MetaGrammarInfo.SYNTHESIS -> visit_SYNTHESIS(node as ASTNode.TerminalNode<MetaGrammarInfo.SYNTHESIS>)
            MetaGrammarInfo.INHERITANCE -> visit_INHERITANCE(node as ASTNode.TerminalNode<MetaGrammarInfo.INHERITANCE>)
            MetaGrammarInfo.COMPUTE -> visit_COMPUTE(node as ASTNode.TerminalNode<MetaGrammarInfo.COMPUTE>)
            MetaGrammarInfo.START -> visit_START(node as ASTNode.TerminalNode<MetaGrammarInfo.START>)
            MetaGrammarInfo.DEFAULT -> visit_DEFAULT(node as ASTNode.TerminalNode<MetaGrammarInfo.DEFAULT>)
            MetaGrammarInfo.INT_TYPE -> visit_INT_TYPE(node as ASTNode.TerminalNode<MetaGrammarInfo.INT_TYPE>)
            MetaGrammarInfo.DOUBLE_TYPE -> visit_DOUBLE_TYPE(node as ASTNode.TerminalNode<MetaGrammarInfo.DOUBLE_TYPE>)
            MetaGrammarInfo.STRING_TYPE -> visit_STRING_TYPE(node as ASTNode.TerminalNode<MetaGrammarInfo.STRING_TYPE>)
            MetaGrammarInfo.KOTLIN_FUNC -> visit_KOTLIN_FUNC(node as ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.KOTLIN_FUNC>>)
            MetaGrammarInfo.DOUBLE -> visit_DOUBLE(node as ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.DOUBLE>>)
            MetaGrammarInfo.INT -> visit_INT(node as ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.INT>>)
            MetaGrammarInfo.CHAR -> visit_CHAR(node as ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.CHAR>>)
            MetaGrammarInfo.STRING -> visit_STRING(node as ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.STRING>>)
            MetaGrammarInfo.RSTRING -> visit_RSTRING(node as ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.RSTRING>>)
            MetaGrammarInfo.MACROREF -> visit_MACROREF(node as ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.MACROREF>>)
            MetaGrammarInfo.SPNAME -> visit_SPNAME(node as ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.SPNAME>>)
            MetaGrammarInfo.CAMELNAME -> visit_CAMELNAME(node as ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.CAMELNAME>>)
            MetaGrammarInfo.CAPSNAME -> visit_CAPSNAME(node as ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.CAPSNAME>>)
            MetaGrammarInfo.WHITESPACE -> visit_WHITESPACE(node as ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.WHITESPACE>>)
            MetaGrammarInfo.all -> visit_all(node as ASTNode.InnerNode<MetaGrammarInfo.all>)
            MetaGrammarInfo.m -> visit_m(node as ASTNode.InnerNode<MetaGrammarInfo.m>)
            MetaGrammarInfo.kfPlus -> visit_kfPlus(node as ASTNode.InnerNode<MetaGrammarInfo.kfPlus>)
            MetaGrammarInfo.t -> visit_t(node as ASTNode.InnerNode<MetaGrammarInfo.t>)
            MetaGrammarInfo.tComp -> visit_tComp(node as ASTNode.InnerNode<MetaGrammarInfo.tComp>)
            MetaGrammarInfo.tSkip -> visit_tSkip(node as ASTNode.InnerNode<MetaGrammarInfo.tSkip>)
            MetaGrammarInfo.tArray -> visit_tArray(node as ASTNode.InnerNode<MetaGrammarInfo.tArray>)
            MetaGrammarInfo.tArrayPlus -> visit_tArrayPlus(node as ASTNode.InnerNode<MetaGrammarInfo.tArrayPlus>)
            MetaGrammarInfo.tFrag -> visit_tFrag(node as ASTNode.InnerNode<MetaGrammarInfo.tFrag>)
            MetaGrammarInfo.tFragLine -> visit_tFragLine(node as ASTNode.InnerNode<MetaGrammarInfo.tFragLine>)
            MetaGrammarInfo.tFragPlus -> visit_tFragPlus(node as ASTNode.InnerNode<MetaGrammarInfo.tFragPlus>)
            MetaGrammarInfo.tLine -> visit_tLine(node as ASTNode.InnerNode<MetaGrammarInfo.tLine>)
            MetaGrammarInfo.tDef -> visit_tDef(node as ASTNode.InnerNode<MetaGrammarInfo.tDef>)
            MetaGrammarInfo.tPlus -> visit_tPlus(node as ASTNode.InnerNode<MetaGrammarInfo.tPlus>)
            MetaGrammarInfo.g -> visit_g(node as ASTNode.InnerNode<MetaGrammarInfo.g>)
            MetaGrammarInfo.gComp -> visit_gComp(node as ASTNode.InnerNode<MetaGrammarInfo.gComp>)
            MetaGrammarInfo.gSynth -> visit_gSynth(node as ASTNode.InnerNode<MetaGrammarInfo.gSynth>)
            MetaGrammarInfo.gInh -> visit_gInh(node as ASTNode.InnerNode<MetaGrammarInfo.gInh>)
            MetaGrammarInfo.gCompv -> visit_gCompv(node as ASTNode.InnerNode<MetaGrammarInfo.gCompv>)
            MetaGrammarInfo.gStart -> visit_gStart(node as ASTNode.InnerNode<MetaGrammarInfo.gStart>)
            MetaGrammarInfo.gLine -> visit_gLine(node as ASTNode.InnerNode<MetaGrammarInfo.gLine>)
            MetaGrammarInfo.gPlus -> visit_gPlus(node as ASTNode.InnerNode<MetaGrammarInfo.gPlus>)
            MetaGrammarInfo.attribs -> visit_attribs(node as ASTNode.InnerNode<MetaGrammarInfo.attribs>)
            MetaGrammarInfo.attrib -> visit_attrib(node as ASTNode.InnerNode<MetaGrammarInfo.attrib>)
            MetaGrammarInfo.attribsPlus -> visit_attribsPlus(node as ASTNode.InnerNode<MetaGrammarInfo.attribsPlus>)
            MetaGrammarInfo.type -> visit_type(node as ASTNode.InnerNode<MetaGrammarInfo.type>)
            MetaGrammarInfo.rules -> visit_rules(node as ASTNode.InnerNode<MetaGrammarInfo.rules>)
            MetaGrammarInfo.rule -> visit_rule(node as ASTNode.InnerNode<MetaGrammarInfo.rule>)
            MetaGrammarInfo.rulesPlus -> visit_rulesPlus(node as ASTNode.InnerNode<MetaGrammarInfo.rulesPlus>)
            MetaGrammarInfo.def -> visit_def(node as ASTNode.InnerNode<MetaGrammarInfo.def>)
            MetaGrammarInfo.pass -> visit_pass(node as ASTNode.InnerNode<MetaGrammarInfo.pass>)
            MetaGrammarInfo.defBody -> visit_defBody(node as ASTNode.InnerNode<MetaGrammarInfo.defBody>)
            MetaGrammarInfo.defAtom -> visit_defAtom(node as ASTNode.InnerNode<MetaGrammarInfo.defAtom>)
            MetaGrammarInfo.defValue -> visit_defValue(node as ASTNode.InnerNode<MetaGrammarInfo.defValue>)
            MetaGrammarInfo.defTerm -> visit_defTerm(node as ASTNode.InnerNode<MetaGrammarInfo.defTerm>)
            MetaGrammarInfo.defMod -> visit_defMod(node as ASTNode.InnerNode<MetaGrammarInfo.defMod>)
            MetaGrammarInfo.setDef -> visit_setDef(node as ASTNode.InnerNode<MetaGrammarInfo.setDef>)
            MetaGrammarInfo.op -> visit_op(node as ASTNode.InnerNode<MetaGrammarInfo.op>)
            MetaGrammarInfo.defPlus -> visit_defPlus(node as ASTNode.InnerNode<MetaGrammarInfo.defPlus>)
            MetaGrammarInfo.seq -> visit_seq(node as ASTNode.InnerNode<MetaGrammarInfo.seq>)
            MetaGrammarInfo.atom -> visit_atom(node as ASTNode.InnerNode<MetaGrammarInfo.atom>)
            MetaGrammarInfo.seqPlus -> visit_seqPlus(node as ASTNode.InnerNode<MetaGrammarInfo.seqPlus>)
            MetaGrammarInfo.atName -> visit_atName(node as ASTNode.InnerNode<MetaGrammarInfo.atName>)
            else -> throw IllegalStateException("Unknown token ${node.getToken()} met")
        }
    }

    fun visit_LPAREN(node: ASTNode.TerminalNode<MetaGrammarInfo.LPAREN>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_RPAREN(node: ASTNode.TerminalNode<MetaGrammarInfo.RPAREN>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_EOLN(node: ASTNode.TerminalNode<MetaGrammarInfo.EOLN>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_DEFINE(node: ASTNode.TerminalNode<MetaGrammarInfo.DEFINE>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_DESCRIBE(node: ASTNode.TerminalNode<MetaGrammarInfo.DESCRIBE>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_CHOICE(node: ASTNode.TerminalNode<MetaGrammarInfo.CHOICE>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_LTRIG(node: ASTNode.TerminalNode<MetaGrammarInfo.LTRIG>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_RTRIG(node: ASTNode.TerminalNode<MetaGrammarInfo.RTRIG>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_CHARRANGE(node: ASTNode.TerminalNode<MetaGrammarInfo.CHARRANGE>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_ASSIGN(node: ASTNode.TerminalNode<MetaGrammarInfo.ASSIGN>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_ADD(node: ASTNode.TerminalNode<MetaGrammarInfo.ADD>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_SUB(node: ASTNode.TerminalNode<MetaGrammarInfo.SUB>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_MUL(node: ASTNode.TerminalNode<MetaGrammarInfo.MUL>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_DIV(node: ASTNode.TerminalNode<MetaGrammarInfo.DIV>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_LARRAY(node: ASTNode.TerminalNode<MetaGrammarInfo.LARRAY>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_RARRAY(node: ASTNode.TerminalNode<MetaGrammarInfo.RARRAY>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_SEP(node: ASTNode.TerminalNode<MetaGrammarInfo.SEP>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_LBRACKET(node: ASTNode.TerminalNode<MetaGrammarInfo.LBRACKET>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_RBRACKET(node: ASTNode.TerminalNode<MetaGrammarInfo.RBRACKET>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_MACRO(node: ASTNode.TerminalNode<MetaGrammarInfo.MACRO>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_TOKENS(node: ASTNode.TerminalNode<MetaGrammarInfo.TOKENS>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_GRAMMAR(node: ASTNode.TerminalNode<MetaGrammarInfo.GRAMMAR>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_FRAGMENTS(node: ASTNode.TerminalNode<MetaGrammarInfo.FRAGMENTS>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_COMPANION(node: ASTNode.TerminalNode<MetaGrammarInfo.COMPANION>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_SKIP(node: ASTNode.TerminalNode<MetaGrammarInfo.SKIP>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_SYNTHESIS(node: ASTNode.TerminalNode<MetaGrammarInfo.SYNTHESIS>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_INHERITANCE(node: ASTNode.TerminalNode<MetaGrammarInfo.INHERITANCE>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_COMPUTE(node: ASTNode.TerminalNode<MetaGrammarInfo.COMPUTE>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_START(node: ASTNode.TerminalNode<MetaGrammarInfo.START>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_DEFAULT(node: ASTNode.TerminalNode<MetaGrammarInfo.DEFAULT>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_INT_TYPE(node: ASTNode.TerminalNode<MetaGrammarInfo.INT_TYPE>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_DOUBLE_TYPE(node: ASTNode.TerminalNode<MetaGrammarInfo.DOUBLE_TYPE>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_STRING_TYPE(node: ASTNode.TerminalNode<MetaGrammarInfo.STRING_TYPE>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_KOTLIN_FUNC(node: ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.KOTLIN_FUNC>>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_DOUBLE(node: ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.DOUBLE>>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_INT(node: ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.INT>>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_CHAR(node: ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.CHAR>>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_STRING(node: ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.STRING>>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_RSTRING(node: ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.RSTRING>>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_MACROREF(node: ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.MACROREF>>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_SPNAME(node: ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.SPNAME>>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_CAMELNAME(node: ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.CAMELNAME>>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_CAPSNAME(node: ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.CAPSNAME>>): R {
        return visitTerminal(node.getToken())
    }

    fun visit_WHITESPACE(node: ASTNode.TerminalNode<Token.VariantToken.VariantInstanceToken<MetaGrammarInfo.WHITESPACE>>): R {
        return visitTerminal(node.getToken())
    }

    /**
    all -> m t g
    */
    fun visit_all(node: ASTNode.InnerNode<MetaGrammarInfo.all>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    fun visit_m(node: ASTNode.InnerNode<MetaGrammarInfo.m>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_m_0(node)
            1 -> visit_m_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of m")
        }
    }

    /**
    m -> MACRO LPAREN kfPlus RPAREN
    */
    fun visit_m_0(node: ASTNode.InnerNode<MetaGrammarInfo.m>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    m -> <eps>
    */
    fun visit_m_1(node: ASTNode.InnerNode<MetaGrammarInfo.m>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_kfPlus(node: ASTNode.InnerNode<MetaGrammarInfo.kfPlus>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_kfPlus_0(node)
            1 -> visit_kfPlus_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of kfPlus")
        }
    }

    /**
    kfPlus -> KOTLIN_FUNC kfPlus
    */
    fun visit_kfPlus_0(node: ASTNode.InnerNode<MetaGrammarInfo.kfPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    kfPlus -> <eps>
    */
    fun visit_kfPlus_1(node: ASTNode.InnerNode<MetaGrammarInfo.kfPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    t -> TOKENS LPAREN tComp tFrag tPlus RPAREN
    */
    fun visit_t(node: ASTNode.InnerNode<MetaGrammarInfo.t>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    fun visit_tComp(node: ASTNode.InnerNode<MetaGrammarInfo.tComp>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_tComp_0(node)
            1 -> visit_tComp_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of tComp")
        }
    }

    /**
    tComp -> COMPANION LPAREN tSkip RPAREN
    */
    fun visit_tComp_0(node: ASTNode.InnerNode<MetaGrammarInfo.tComp>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    tComp -> <eps>
    */
    fun visit_tComp_1(node: ASTNode.InnerNode<MetaGrammarInfo.tComp>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    tSkip -> SKIP DESCRIBE tArray EOLN
    */
    fun visit_tSkip(node: ASTNode.InnerNode<MetaGrammarInfo.tSkip>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    /**
    tArray -> LARRAY CAPSNAME tArrayPlus RARRAY
    */
    fun visit_tArray(node: ASTNode.InnerNode<MetaGrammarInfo.tArray>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    fun visit_tArrayPlus(node: ASTNode.InnerNode<MetaGrammarInfo.tArrayPlus>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_tArrayPlus_0(node)
            1 -> visit_tArrayPlus_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of tArrayPlus")
        }
    }

    /**
    tArrayPlus -> SEP CAPSNAME tArrayPlus
    */
    fun visit_tArrayPlus_0(node: ASTNode.InnerNode<MetaGrammarInfo.tArrayPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    tArrayPlus -> <eps>
    */
    fun visit_tArrayPlus_1(node: ASTNode.InnerNode<MetaGrammarInfo.tArrayPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_tFrag(node: ASTNode.InnerNode<MetaGrammarInfo.tFrag>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_tFrag_0(node)
            1 -> visit_tFrag_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of tFrag")
        }
    }

    /**
    tFrag -> FRAGMENTS LPAREN tFragPlus RPAREN
    */
    fun visit_tFrag_0(node: ASTNode.InnerNode<MetaGrammarInfo.tFrag>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    tFrag -> <eps>
    */
    fun visit_tFrag_1(node: ASTNode.InnerNode<MetaGrammarInfo.tFrag>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    tFragLine -> CAPSNAME DESCRIBE STRING EOLN
    */
    fun visit_tFragLine(node: ASTNode.InnerNode<MetaGrammarInfo.tFragLine>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    fun visit_tFragPlus(node: ASTNode.InnerNode<MetaGrammarInfo.tFragPlus>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_tFragPlus_0(node)
            1 -> visit_tFragPlus_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of tFragPlus")
        }
    }

    /**
    tFragPlus -> tFragLine tFragPlus
    */
    fun visit_tFragPlus_0(node: ASTNode.InnerNode<MetaGrammarInfo.tFragPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    tFragPlus -> <eps>
    */
    fun visit_tFragPlus_1(node: ASTNode.InnerNode<MetaGrammarInfo.tFragPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    tLine -> CAPSNAME DESCRIBE tDef EOLN
    */
    fun visit_tLine(node: ASTNode.InnerNode<MetaGrammarInfo.tLine>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    fun visit_tDef(node: ASTNode.InnerNode<MetaGrammarInfo.tDef>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_tDef_0(node)
            1 -> visit_tDef_1(node)
            2 -> visit_tDef_2(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of tDef")
        }
    }

    /**
    tDef -> STRING
    */
    fun visit_tDef_0(node: ASTNode.InnerNode<MetaGrammarInfo.tDef>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    tDef -> RSTRING
    */
    fun visit_tDef_1(node: ASTNode.InnerNode<MetaGrammarInfo.tDef>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    tDef -> LTRIG CHAR CHARRANGE CHAR RTRIG
    */
    fun visit_tDef_2(node: ASTNode.InnerNode<MetaGrammarInfo.tDef>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_tPlus(node: ASTNode.InnerNode<MetaGrammarInfo.tPlus>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_tPlus_0(node)
            1 -> visit_tPlus_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of tPlus")
        }
    }

    /**
    tPlus -> tLine tPlus
    */
    fun visit_tPlus_0(node: ASTNode.InnerNode<MetaGrammarInfo.tPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    tPlus -> <eps>
    */
    fun visit_tPlus_1(node: ASTNode.InnerNode<MetaGrammarInfo.tPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    g -> GRAMMAR LPAREN gComp gPlus RPAREN
    */
    fun visit_g(node: ASTNode.InnerNode<MetaGrammarInfo.g>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    /**
    gComp -> COMPANION LPAREN gSynth gInh gCompv gStart RPAREN
    */
    fun visit_gComp(node: ASTNode.InnerNode<MetaGrammarInfo.gComp>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    fun visit_gSynth(node: ASTNode.InnerNode<MetaGrammarInfo.gSynth>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_gSynth_0(node)
            1 -> visit_gSynth_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of gSynth")
        }
    }

    /**
    gSynth -> SYNTHESIS LPAREN attribs RPAREN
    */
    fun visit_gSynth_0(node: ASTNode.InnerNode<MetaGrammarInfo.gSynth>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    gSynth -> <eps>
    */
    fun visit_gSynth_1(node: ASTNode.InnerNode<MetaGrammarInfo.gSynth>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_gInh(node: ASTNode.InnerNode<MetaGrammarInfo.gInh>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_gInh_0(node)
            1 -> visit_gInh_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of gInh")
        }
    }

    /**
    gInh -> INHERITANCE LPAREN attribs RPAREN
    */
    fun visit_gInh_0(node: ASTNode.InnerNode<MetaGrammarInfo.gInh>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    gInh -> <eps>
    */
    fun visit_gInh_1(node: ASTNode.InnerNode<MetaGrammarInfo.gInh>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_gCompv(node: ASTNode.InnerNode<MetaGrammarInfo.gCompv>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_gCompv_0(node)
            1 -> visit_gCompv_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of gCompv")
        }
    }

    /**
    gCompv -> COMPUTE LPAREN attribs RPAREN
    */
    fun visit_gCompv_0(node: ASTNode.InnerNode<MetaGrammarInfo.gCompv>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    gCompv -> <eps>
    */
    fun visit_gCompv_1(node: ASTNode.InnerNode<MetaGrammarInfo.gCompv>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    gStart -> START DESCRIBE CAMELNAME EOLN
    */
    fun visit_gStart(node: ASTNode.InnerNode<MetaGrammarInfo.gStart>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    /**
    gLine -> CAMELNAME def DESCRIBE rules EOLN
    */
    fun visit_gLine(node: ASTNode.InnerNode<MetaGrammarInfo.gLine>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    fun visit_gPlus(node: ASTNode.InnerNode<MetaGrammarInfo.gPlus>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_gPlus_0(node)
            1 -> visit_gPlus_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of gPlus")
        }
    }

    /**
    gPlus -> gLine gPlus
    */
    fun visit_gPlus_0(node: ASTNode.InnerNode<MetaGrammarInfo.gPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    gPlus -> <eps>
    */
    fun visit_gPlus_1(node: ASTNode.InnerNode<MetaGrammarInfo.gPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    attribs -> attrib attribsPlus
    */
    fun visit_attribs(node: ASTNode.InnerNode<MetaGrammarInfo.attribs>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    /**
    attrib -> CAMELNAME DESCRIBE type setDef EOLN
    */
    fun visit_attrib(node: ASTNode.InnerNode<MetaGrammarInfo.attrib>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    fun visit_attribsPlus(node: ASTNode.InnerNode<MetaGrammarInfo.attribsPlus>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_attribsPlus_0(node)
            1 -> visit_attribsPlus_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of attribsPlus")
        }
    }

    /**
    attribsPlus -> attrib attribsPlus
    */
    fun visit_attribsPlus_0(node: ASTNode.InnerNode<MetaGrammarInfo.attribsPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    attribsPlus -> <eps>
    */
    fun visit_attribsPlus_1(node: ASTNode.InnerNode<MetaGrammarInfo.attribsPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_type(node: ASTNode.InnerNode<MetaGrammarInfo.type>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_type_0(node)
            1 -> visit_type_1(node)
            2 -> visit_type_2(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of type")
        }
    }

    /**
    type -> INT_TYPE
    */
    fun visit_type_0(node: ASTNode.InnerNode<MetaGrammarInfo.type>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    type -> DOUBLE_TYPE
    */
    fun visit_type_1(node: ASTNode.InnerNode<MetaGrammarInfo.type>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    type -> STRING_TYPE
    */
    fun visit_type_2(node: ASTNode.InnerNode<MetaGrammarInfo.type>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    rules -> rule rulesPlus
    */
    fun visit_rules(node: ASTNode.InnerNode<MetaGrammarInfo.rules>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    /**
    rule -> seq def
    */
    fun visit_rule(node: ASTNode.InnerNode<MetaGrammarInfo.rule>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    fun visit_rulesPlus(node: ASTNode.InnerNode<MetaGrammarInfo.rulesPlus>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_rulesPlus_0(node)
            1 -> visit_rulesPlus_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of rulesPlus")
        }
    }

    /**
    rulesPlus -> CHOICE rule rulesPlus
    */
    fun visit_rulesPlus_0(node: ASTNode.InnerNode<MetaGrammarInfo.rulesPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    rulesPlus -> <eps>
    */
    fun visit_rulesPlus_1(node: ASTNode.InnerNode<MetaGrammarInfo.rulesPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_def(node: ASTNode.InnerNode<MetaGrammarInfo.def>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_def_0(node)
            1 -> visit_def_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of def")
        }
    }

    /**
    def -> DEFINE LPAREN defBody RPAREN
    */
    fun visit_def_0(node: ASTNode.InnerNode<MetaGrammarInfo.def>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    def -> <eps>
    */
    fun visit_def_1(node: ASTNode.InnerNode<MetaGrammarInfo.def>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_pass(node: ASTNode.InnerNode<MetaGrammarInfo.pass>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_pass_0(node)
            1 -> visit_pass_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of pass")
        }
    }

    /**
    pass -> LPAREN defBody RPAREN
    */
    fun visit_pass_0(node: ASTNode.InnerNode<MetaGrammarInfo.pass>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    pass -> <eps>
    */
    fun visit_pass_1(node: ASTNode.InnerNode<MetaGrammarInfo.pass>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    defBody -> defAtom defPlus
    */
    fun visit_defBody(node: ASTNode.InnerNode<MetaGrammarInfo.defBody>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    /**
    defAtom -> CAMELNAME ASSIGN defValue
    */
    fun visit_defAtom(node: ASTNode.InnerNode<MetaGrammarInfo.defAtom>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    fun visit_defValue(node: ASTNode.InnerNode<MetaGrammarInfo.defValue>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_defValue_0(node)
            1 -> visit_defValue_1(node)
            2 -> visit_defValue_2(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of defValue")
        }
    }

    /**
    defValue -> STRING
    */
    fun visit_defValue_0(node: ASTNode.InnerNode<MetaGrammarInfo.defValue>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    defValue -> defTerm defMod
    */
    fun visit_defValue_1(node: ASTNode.InnerNode<MetaGrammarInfo.defValue>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    defValue -> SUB defTerm
    */
    fun visit_defValue_2(node: ASTNode.InnerNode<MetaGrammarInfo.defValue>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_defTerm(node: ASTNode.InnerNode<MetaGrammarInfo.defTerm>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_defTerm_0(node)
            1 -> visit_defTerm_1(node)
            2 -> visit_defTerm_2(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of defTerm")
        }
    }

    /**
    defTerm -> atName
    */
    fun visit_defTerm_0(node: ASTNode.InnerNode<MetaGrammarInfo.defTerm>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    defTerm -> INT
    */
    fun visit_defTerm_1(node: ASTNode.InnerNode<MetaGrammarInfo.defTerm>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    defTerm -> DOUBLE
    */
    fun visit_defTerm_2(node: ASTNode.InnerNode<MetaGrammarInfo.defTerm>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_defMod(node: ASTNode.InnerNode<MetaGrammarInfo.defMod>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_defMod_0(node)
            1 -> visit_defMod_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of defMod")
        }
    }

    /**
    defMod -> op defTerm
    */
    fun visit_defMod_0(node: ASTNode.InnerNode<MetaGrammarInfo.defMod>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    defMod -> <eps>
    */
    fun visit_defMod_1(node: ASTNode.InnerNode<MetaGrammarInfo.defMod>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_setDef(node: ASTNode.InnerNode<MetaGrammarInfo.setDef>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_setDef_0(node)
            1 -> visit_setDef_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of setDef")
        }
    }

    /**
    setDef -> DEFINE LPAREN DEFAULT ASSIGN defValue RPAREN
    */
    fun visit_setDef_0(node: ASTNode.InnerNode<MetaGrammarInfo.setDef>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    setDef -> <eps>
    */
    fun visit_setDef_1(node: ASTNode.InnerNode<MetaGrammarInfo.setDef>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_op(node: ASTNode.InnerNode<MetaGrammarInfo.op>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_op_0(node)
            1 -> visit_op_1(node)
            2 -> visit_op_2(node)
            3 -> visit_op_3(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of op")
        }
    }

    /**
    op -> ADD
    */
    fun visit_op_0(node: ASTNode.InnerNode<MetaGrammarInfo.op>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    op -> SUB
    */
    fun visit_op_1(node: ASTNode.InnerNode<MetaGrammarInfo.op>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    op -> MUL
    */
    fun visit_op_2(node: ASTNode.InnerNode<MetaGrammarInfo.op>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    op -> DIV
    */
    fun visit_op_3(node: ASTNode.InnerNode<MetaGrammarInfo.op>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_defPlus(node: ASTNode.InnerNode<MetaGrammarInfo.defPlus>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_defPlus_0(node)
            1 -> visit_defPlus_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of defPlus")
        }
    }

    /**
    defPlus -> SEP defAtom defPlus
    */
    fun visit_defPlus_0(node: ASTNode.InnerNode<MetaGrammarInfo.defPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    defPlus -> <eps>
    */
    fun visit_defPlus_1(node: ASTNode.InnerNode<MetaGrammarInfo.defPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    seq -> atom seqPlus
    */
    fun visit_seq(node: ASTNode.InnerNode<MetaGrammarInfo.seq>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree")
    }

    fun visit_atom(node: ASTNode.InnerNode<MetaGrammarInfo.atom>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_atom_0(node)
            1 -> visit_atom_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of atom")
        }
    }

    /**
    atom -> CAPSNAME
    */
    fun visit_atom_0(node: ASTNode.InnerNode<MetaGrammarInfo.atom>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    atom -> CAMELNAME pass
    */
    fun visit_atom_1(node: ASTNode.InnerNode<MetaGrammarInfo.atom>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_seqPlus(node: ASTNode.InnerNode<MetaGrammarInfo.seqPlus>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_seqPlus_0(node)
            1 -> visit_seqPlus_1(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of seqPlus")
        }
    }

    /**
    seqPlus -> atom seqPlus
    */
    fun visit_seqPlus_0(node: ASTNode.InnerNode<MetaGrammarInfo.seqPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    seqPlus -> <eps>
    */
    fun visit_seqPlus_1(node: ASTNode.InnerNode<MetaGrammarInfo.seqPlus>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    fun visit_atName(node: ASTNode.InnerNode<MetaGrammarInfo.atName>): R {
        return when (val id = node.getExpansion().getId()) {
            0 -> visit_atName_0(node)
            1 -> visit_atName_1(node)
            2 -> visit_atName_2(node)
            else -> throw IllegalStateException("Unexpected expansion id $id in expansion of atName")
        }
    }

    /**
    atName -> SPNAME
    */
    fun visit_atName_0(node: ASTNode.InnerNode<MetaGrammarInfo.atName>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    atName -> CAMELNAME
    */
    fun visit_atName_1(node: ASTNode.InnerNode<MetaGrammarInfo.atName>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

    /**
    atName -> MACROREF CAMELNAME LBRACKET defValue RBRACKET
    */
    fun visit_atName_2(node: ASTNode.InnerNode<MetaGrammarInfo.atName>): R {
        throw IllegalStateException("Unexpected expansion ${node.getToken()} -> ${node.getExpansion()} visited while traversing tree") 
    }

}